samtools flagstat -@ 8 A2_H2MVWDMXX_L1.bam > A2_H2MVWDMXX_L1.bam.stat
samtools flagstat -@ 8 B_H2NJFDMXX_L1.bam > B_H2NJFDMXX_L1.bam.stat
samtools flagstat -@ 8 C_H3JFKDMXX_L1.bam > C_H3JFKDMXX_L1.bam.stat
samtools flagstat -@ 8 D_H3JFKDMXX_L1.bam > D_H3JFKDMXX_L1.bam.stat
samtools flagstat -@ 8 E_H3JC2DMXX_L1.bam > E_H3JC2DMXX_L1.bam.stat
samtools flagstat -@ 8 F_H3JFKDMXX_L1.bam > F_H3JFKDMXX_L1.bam.stat
samtools flagstat -@ 8 G_H3JC2DMXX_L1.bam > G_H3JC2DMXX_L1.bam.stat
samtools flagstat -@ 8 H_H3JFKDMXX_L1.bam > H_H3JFKDMXX_L1.bam.stat
samtools flagstat -@ 8 I_H3JC2DMXX_L1.bam > I_H3JC2DMXX_L1.bam.stat
samtools flagstat -@ 8 J_H3JCWDMXX_L1.bam > J_H3JCWDMXX_L1.bam.stat
