samtools depth -r MDR-CQ A2_H2MVWDMXX_L1.bam > A2_H2MVWDMXX_L1.bam.depth
samtools depth -r MDR-CQ B_H2NJFDMXX_L1.bam > B_H2NJFDMXX_L1.bam.depth
samtools depth -r MDR-CQ C_H3JFKDMXX_L1.bam > C_H3JFKDMXX_L1.bam.depth
samtools depth -r MDR-CQ D_H3JFKDMXX_L1.bam > D_H3JFKDMXX_L1.bam.depth
samtools depth -r MDR-CQ E_H3JC2DMXX_L1.bam > E_H3JC2DMXX_L1.bam.depth
samtools depth -r MDR-CQ F_H3JFKDMXX_L1.bam > F_H3JFKDMXX_L1.bam.depth
samtools depth -r MDR-CQ G_H3JC2DMXX_L1.bam > G_H3JC2DMXX_L1.bam.depth
samtools depth -r MDR-CQ H_H3JFKDMXX_L1.bam > H_H3JFKDMXX_L1.bam.depth
samtools depth -r MDR-CQ I_H3JC2DMXX_L1.bam > I_H3JC2DMXX_L1.bam.depth
samtools depth -r MDR-CQ J_H3JCWDMXX_L1.bam > J_H3JCWDMXX_L1.bam.depth
